MCU = RP2040
BOOTLOADER = rp2040
BOARD = GENERIC_RP_RP2040

BOOTMAGIC_ENABLE = yes
NKRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
OLED_ENABLE = yes

I2C_DRIVER = vendor
EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = rp2040_flash
LTO_ENABLE = yes
